use clap::Parser;
use tracing::{info, error, warn};
use veryslip_client::config::Config;
use std::path::PathBuf;
use std::sync::Arc;
use tokio::signal;

#[derive(Parser, Debug)]
#[command(name = "veryslip-client")]
#[command(version = env!("CARGO_PKG_VERSION"))]
#[command(about = "Very Slip Client - High-performance DNS tunnel client", long_about = None)]
struct Args {
    /// Path to configuration file
    #[arg(short, long)]
    config: Option<PathBuf>,

    /// Generate default configuration
    #[arg(long)]
    generate_config: bool,

    /// Validate configuration file
    #[arg(long)]
    validate_config: bool,

    /// Log level (error, warn, info, debug, trace)
    #[arg(long, default_value = "info")]
    log_level: String,
}

#[tokio::main]
async fn main() {
    if let Err(e) = run().await {
        eprintln!("Fatal error: {}", e);
        std::process::exit(1);
    }
}

async fn run() -> veryslip_client::Result<()> {
    let args = Args::parse();

    // Handle generate-config flag
    if args.generate_config {
        println!("# Very Slip Client Configuration");
        println!("# Generated by veryslip-client v{}", env!("CARGO_PKG_VERSION"));
        println!();
        println!("{}", Config::generate_default());
        return Ok(());
    }

    // Determine config path
    let config_path = args.config.clone().unwrap_or_else(|| {
        veryslip_client::config::config_dir().join("config.toml")
    });

    // Handle validate-config flag
    if args.validate_config {
        match Config::load(&config_path) {
            Ok(config) => {
                match config.validate() {
                    Ok(_) => {
                        println!("✓ Configuration is valid");
                        println!("  Domains: {}", config.domains.len());
                        println!("  Resolvers: {}", config.resolvers.len());
                        println!("  Proxy port: {}", config.proxy.port);
                        std::process::exit(0);
                    }
                    Err(e) => {
                        eprintln!("✗ Configuration validation failed: {}", e);
                        std::process::exit(1);
                    }
                }
            }
            Err(e) => {
                eprintln!("✗ Failed to load configuration: {}", e);
                std::process::exit(1);
            }
        }
    }

    // Initialize logging
    let log_config = veryslip_client::logging::LogConfig {
        level: args.log_level.clone(),
        format: veryslip_client::logging::LogFormat::Text,
        output: veryslip_client::logging::LogOutput::Stdout,
        file_path: None,
        rotation_size: 100 * 1024 * 1024,
        max_files: 5,
    };
    
    veryslip_client::logging::init_logging(&log_config)?;

    info!("Very Slip Client v{} starting...", env!("CARGO_PKG_VERSION"));
    info!("Platform: {}", std::env::consts::OS);
    info!("Architecture: {}", std::env::consts::ARCH);

    // Load configuration
    let config = match Config::load(&config_path) {
        Ok(config) => {
            info!("Configuration loaded from: {:?}", config_path);
            config
        }
        Err(e) => {
            error!("Failed to load configuration from {:?}: {}", config_path, e);
            error!("Run with --generate-config to create a default configuration");
            error!("Example: veryslip-client --generate-config > config.toml");
            std::process::exit(1);
        }
    };

    // Validate configuration
    if let Err(e) = config.validate() {
        error!("Configuration validation failed: {}", e);
        std::process::exit(1);
    }

    info!("Configuration validated successfully");
    info!("  Domains: {} configured", config.domains.len());
    info!("  Resolvers: {} configured", config.resolvers.len());
    info!("  Proxy port: {}", config.proxy.port);
    info!("  Compression: {}", if config.compression.enabled { "enabled" } else { "disabled" });
    info!("  Cache: {} (max {}MB)", 
        if config.cache.enabled { "enabled" } else { "disabled" },
        config.cache.max_memory_size / (1024 * 1024)
    );
    info!("  Prefetch: {}", if config.prefetch.enabled { "enabled" } else { "disabled" });
    info!("  Ad blocking: {}", if config.filter.enabled { "enabled" } else { "disabled" });
    info!("  DoH: {}", if config.doh.enabled { "enabled" } else { "disabled (using UDP DNS)" });

    // Create platform-specific directories
    create_directories()?;

    // Initialize all components
    info!("Initializing components...");
    
    // Filter engine
    let filter = veryslip_client::filter::FilterEngine::new();
    if config.filter.enabled {
        if let Some(ref blocklist_path) = config.filter.blocklist_path {
            match filter.load_blocklist(blocklist_path) {
                Ok(_) => info!("  Filter: loaded blocklist"),
                Err(e) => warn!("  Filter: failed to load blocklist: {}", e),
            }
        }
    }
    let filter = Arc::new(filter);
    
    // Cache manager
    let cache_config = veryslip_client::cache::CacheConfig {
        max_memory_size: config.cache.max_memory_size,
        disk_path: config.cache.disk_path.clone().unwrap_or_else(|| {
            veryslip_client::config::config_dir().join("cache")
        }),
        default_ttl: std::time::Duration::from_secs(3600),
    };
    let cache = Arc::new(veryslip_client::cache::CacheManager::new(cache_config)?);
    info!("  Cache: initialized");
    
    // Priority queue
    let priority_config = veryslip_client::priority::PriorityConfig {
        bandwidth_weights: config.priority.bandwidth_weights,
        starvation_timeout: std::time::Duration::from_secs(config.priority.starvation_timeout_secs),
        max_per_queue: 1000,
    };
    let priority_queue = Arc::new(veryslip_client::priority::PriorityQueue::new(priority_config));
    info!("  Priority queue: initialized");
    
    // Compression engine
    let compression_config = veryslip_client::compression::CompressionConfig {
        level: config.compression.level,
        dictionary_path: config.compression.dictionary_path.as_ref().map(|p| p.to_string_lossy().to_string()),
        adaptive: config.compression.adaptive,
    };
    let compression = Arc::new(veryslip_client::compression::CompressionEngine::new(compression_config)?);
    info!("  Compression: initialized (level {})", config.compression.level);
    
    // Load balancer
    let lb_config = veryslip_client::load_balancer::LoadBalancerConfig {
        failure_timeout: std::time::Duration::from_secs(config.load_balancer.failure_timeout_secs),
        window_size: std::time::Duration::from_secs(config.load_balancer.window_size_secs),
        weight_reduction: config.load_balancer.weight_reduction,
        success_threshold: config.load_balancer.success_threshold,
    };
    let load_balancer = Arc::new(veryslip_client::load_balancer::LoadBalancer::new(config.domains.clone(), lb_config));
    info!("  Load balancer: initialized with {} domains", config.domains.len());
    
    // Buffer pool
    let buffer_config = veryslip_client::buffer::BufferPoolConfig {
        initial_size: config.buffer.initial_size,
        max_size: config.buffer.max_size,
        buffer_capacity: config.buffer.buffer_capacity,
    };
    let buffer_pool = Arc::new(veryslip_client::buffer::BufferPool::new(buffer_config));
    info!("  Buffer pool: initialized");
    
    // DoH client pool (optional)
    let doh_client = if config.doh.enabled {
        let doh_configs: Vec<veryslip_client::doh::DohConfig> = config.doh.endpoints
            .iter()
            .map(|endpoint| veryslip_client::doh::DohConfig {
                enabled: true,
                endpoint: endpoint.clone(),
                timeout: std::time::Duration::from_secs(config.doh.timeout_secs),
            })
            .collect();
        
        match veryslip_client::doh::DohClientPool::new(doh_configs) {
            Ok(pool) => {
                info!("  DoH: initialized with {} endpoints", config.doh.endpoints.len());
                Some(Arc::new(pool))
            }
            Err(e) => {
                warn!("  DoH: failed to initialize: {}, falling back to UDP DNS", e);
                None
            }
        }
    } else {
        None
    };
    
    // Query engine
    let query_config = veryslip_client::query::QueryConfig {
        concurrency: config.query.concurrency,
        max_in_flight: config.query.max_in_flight,
        batch_timeout: std::time::Duration::from_millis(config.query.batch_timeout_ms),
        batch_threshold: config.query.batch_threshold,
        query_timeout: std::time::Duration::from_secs(5),
        max_retries: 3,
    };
    let query_engine = if let Some(doh) = doh_client {
        Arc::new(veryslip_client::query::QueryEngine::new_with_doh(
            query_config,
            load_balancer.clone(),
            buffer_pool,
            doh,
            config.doh.use_get_method,
        ))
    } else {
        Arc::new(veryslip_client::query::QueryEngine::new(
            query_config,
            load_balancer.clone(),
            buffer_pool,
        ))
    };
    info!("  Query engine: initialized (concurrency: {})", config.query.concurrency);
    
    // Connection pool (use first domain as server address)
    let server_addr = config.domains.first()
        .ok_or_else(|| veryslip_client::VerySlipError::InvalidState("No domains configured".to_string()))?
        .clone();
    
    let connection_config = veryslip_client::connection::ConnectionPoolConfig {
        max_connections: config.connection.max_connections,
        max_streams_per_conn: 100,
        idle_timeout: std::time::Duration::from_secs(config.connection.idle_timeout_secs),
        quic_config: veryslip_client::connection::QuicConfig::default(),
    };
    let connection_pool = Arc::new(veryslip_client::connection::ConnectionPool::new(connection_config, server_addr)?);
    info!("  Connection pool: initialized");
    
    // Prefetch engine
    let prefetch_config = veryslip_client::prefetch::PrefetchConfig {
        enabled: config.prefetch.enabled,
        max_queue_size: config.prefetch.max_queue_size,
        resource_types: vec![
            veryslip_client::prefetch::ResourceType::Stylesheet,
            veryslip_client::prefetch::ResourceType::Script,
            veryslip_client::prefetch::ResourceType::Image,
        ],
        max_resource_size: 5 * 1024 * 1024,
        allow_cross_origin: false,
    };
    let prefetch = Arc::new(veryslip_client::prefetch::PrefetchEngine::new(
        prefetch_config,
        cache.clone(),
        priority_queue.clone(),
    ));
    info!("  Prefetch: {}", if config.prefetch.enabled { "enabled" } else { "disabled" });
    
    // Pipeline
    let pipeline = Arc::new(veryslip_client::pipeline::Pipeline::new(
        filter,
        cache,
        priority_queue,
        compression,
        query_engine,
        load_balancer,
        connection_pool,
        prefetch,
    ));
    info!("  Pipeline: initialized");
    
    // Metrics collector
    let metrics_config = veryslip_client::metrics::MetricsConfig {
        enabled: config.metrics.enabled,
        http_port: config.metrics.http_port,
        log_interval_secs: config.metrics.log_interval_secs,
    };
    let metrics = Arc::new(veryslip_client::metrics::MetricsCollector::new(metrics_config)?);
    
    if config.metrics.enabled {
        let metrics_http = metrics.clone();
        tokio::spawn(async move {
            if let Err(e) = metrics_http.start_http_server().await {
                error!("Metrics server error: {}", e);
            }
        });
        
        let metrics_log = metrics.clone();
        tokio::spawn(async move {
            metrics_log.start_periodic_logging().await;
        });
        
        info!("  Metrics: enabled (port {})", config.metrics.http_port);
    }
    
    // Proxy server
    let proxy_config = veryslip_client::proxy::ProxyConfig {
        bind_addr: format!("127.0.0.1:{}", config.proxy.port),
        max_connections: 1000,
        auth_enabled: config.proxy.auth_enabled,
        auth_username: config.proxy.username.clone(),
        auth_password: config.proxy.password.clone(),
        idle_timeout: std::time::Duration::from_secs(60),
        total_timeout: std::time::Duration::from_secs(300),
    };
    let proxy = veryslip_client::proxy::ProxyServer::new(proxy_config, pipeline);
    
    info!("All components initialized successfully");
    info!("");
    info!("===========================================");
    info!("  Very Slip Client is ready!");
    info!("===========================================");
    info!("  Proxy: http://127.0.0.1:{}", config.proxy.port);
    if config.metrics.enabled {
        info!("  Metrics: http://127.0.0.1:{}/metrics", config.metrics.http_port);
    }
    info!("  Press Ctrl+C to stop");
    info!("===========================================");
    info!("");

    // Setup signal handlers
    let shutdown = setup_shutdown_handler();

    // Run proxy server
    tokio::select! {
        result = proxy.start() => {
            if let Err(e) = result {
                error!("Proxy server error: {}", e);
                return Err(e);
            }
        }
        _ = shutdown => {
            info!("Shutdown signal received");
        }
    }
    
    // Graceful shutdown
    info!("Shutting down gracefully...");
    info!("  Stopping proxy server...");
    info!("  Flushing cache...");
    info!("  Closing connections...");
    
    // Give components time to clean up
    tokio::time::sleep(tokio::time::Duration::from_secs(2)).await;
    
    info!("Shutdown complete");
    Ok(())
}

/// Create platform-specific directories
fn create_directories() -> veryslip_client::Result<()> {
    let config_dir = veryslip_client::config::config_dir();
    std::fs::create_dir_all(&config_dir)?;
    
    // Create cache directory
    let cache_dir = config_dir.join("cache");
    std::fs::create_dir_all(&cache_dir)?;
    
    // Create state directory
    let state_dir = config_dir.join("state");
    std::fs::create_dir_all(&state_dir)?;
    
    Ok(())
}

/// Setup shutdown signal handler
async fn setup_shutdown_handler() {
    #[cfg(unix)]
    {
        use tokio::signal::unix::{signal, SignalKind};
        
        let mut sigterm = signal(SignalKind::terminate()).expect("Failed to setup SIGTERM handler");
        let mut sigint = signal(SignalKind::interrupt()).expect("Failed to setup SIGINT handler");
        
        tokio::select! {
            _ = sigterm.recv() => {},
            _ = sigint.recv() => {},
        }
    }
    
    #[cfg(not(unix))]
    {
        signal::ctrl_c().await.expect("Failed to setup Ctrl+C handler");
    }
}
